//Création
POST http://localhost:8081/movies
Content-Type: application/json

{"title":"toto", "length":"bobby"}

###

//GET 1
GET http://localhost:8081/movies/1
Content-Type: application/json
###

//Remplace
PUT http://localhost:8081/movies/2
Content-Type: application/json

{"title":"tata", "length":"bobby"}
###

//Mise à jour partielle
PATCH http://localhost:8081/movies/2
Content-Type: application/json

{"title":"blabla"}
###

//GET All
GET http://localhost:8081/movies
Content-Type: application/json
###

//Suppression
DELETE http://localhost:8081/movies/2
Content-Type: application/json

###